WORLD: -1
STAGE: -1
VERSION: 0

SHAPE: 84
SKIP_FRAME: 4
NUM_STACK: 4

IS_RENDER: false
EPISODES: 50000000
EVERY_RECORD: 50
EVERY_RENDER: 1
EVERY_EPISODE_SAVE: 100
EVERY_STEP_SAVE: 100000

INTENTION: |-
  基本の Config
