POSITION:
  MIN: -1
  MAX: 1
ENEMY:
  MIN: -1
  MAX: 1
COIN:
  MIN: -1
  MAX: 1
GOAL:
  MIN: -1
  MAX: 1
LIFE:
  MIN: -1
  MAX: 1
ITEM:
  MIN: -1
  MAX: 1
TIME: # マイナスだとマリオが早くゴールを目指す
  MIN: -1
  MAX: 1
SCORE:
  MIN: -1
  MAX: 1
