ENEMY:
  MIN: -500
  MAX: 500
  USE: true
COIN:
  MIN: -500
  MAX: 500
  USE: true

POSITION:
  USE: false
GOAL:
  USE: false
LIFE:
  USE: false
ITEM:
  USE: false
TIME:
  USE: false
SCORE:
  USE: false
