ENEMY:
  MIN: -100
  MAX: 100
  USE: true
COIN:
  MIN: -100
  MAX: 100
  USE: true

POSITION:
  USE: false
GOAL:
  USE: false
LIFE:
  USE: false
ITEM:
  USE: false
TIME:
  USE: false
SCORE:
  USE: false
