name: test
on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.9]
        poetry-version: [1.1.5]
        os: [ubuntu-18.04, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install
        run: poetry install
      - name: Pytest
        run: pytest tests
